import type { Lead } from './types'

export const mockLeads: Lead[] = [
  {
    id: 'example-lead-1',
    name: 'Example Customer',
    email: 'example.customer@example.com',
    company: 'Example Co',
    phone: '010-0000-0000',
    projectType: 'Website',
    currentStatus: '아이디어만 있음',
    goals: ['회사 소개', '문의 / 상담 전환'],
    budget: '100~300만원',
    timeline: '1개월 이내',
    status: 'NEW',
    createdAt: '2026-09-20',
    targetUsers: ['일반 고객'],
    features: ['Inquiry', 'Content'],
    description: 'Example description for a company site. This fixture is only loaded in development.',
    references: [{ url: 'https://example.com', note: 'Example reference note' }],
  },
  {
    id: 'example-lead-2',
    name: 'Example Founder',
    email: 'example.founder@example.com',
    company: 'Example Studio',
    phone: '010-0000-0001',
    projectType: 'MVP / Web App',
    currentStatus: '요구사항 정리됨',
    goals: ['서비스 출시'],
    budget: '500~800만원',
    timeline: '1~2개월',
    status: 'CONTACTED',
    createdAt: '2026-09-18',
    targetUsers: ['기업 고객', '관리자'],
    features: ['Login', 'Dashboard'],
    description: 'Example product description. Not a real customer.',
    references: [],
  },
]
