import type { Engagement } from './types'

const id = 'example-engagement-1'

export const mockEngagements: Engagement[] = [
  {
    id,
    name: 'Example Website',
    customer: 'Example Customer',
    projectType: 'Website',
    status: 'DEVELOPMENT',
    progress: 45,
    startedAt: '2026-09-20',
    expectedCompletion: '2026-11-15',
    actionRequired: {
      kind: 'REVIEW_REQUIRED',
      label: '디자인 검토',
      description: '디자인 초안을 확인하고 승인하거나 수정 요청을 남겨 주세요.',
      dueDate: '2026-10-05',
      ctaLabel: '검토 열기',
      ctaTarget: `/my/projects/${id}?tab=review`,
    },
    blockedReason: null,
    currentMilestoneId: 'example-milestone-design',
    createdAt: '2026-09-20',
    updatedAt: '2026-09-27',
    contractAgreed: true,
    depositPaid: true,
    internalNotes: 'Example internal note. 고객 화면에는 보이지 않습니다.',
    milestones: [
      {
        id: 'example-milestone-planning',
        engagementId: id,
        title: 'Planning',
        description: '범위와 화면 목록을 정리합니다.',
        status: 'APPROVED',
        order: 1,
        dueDate: '2026-09-25',
        completedAt: '2026-09-25',
        requiresApproval: true,
        notes: '승인된 기획은 잠긴 단계입니다.',
      },
      {
        id: 'example-milestone-design',
        engagementId: id,
        title: 'Design',
        description: '첫 화면과 주요 페이지 시안입니다.',
        status: 'AWAITING_REVIEW',
        order: 2,
        dueDate: '2026-10-05',
        completedAt: null,
        requiresApproval: true,
        notes: '',
      },
      {
        id: 'example-milestone-build',
        engagementId: id,
        title: 'Development',
        description: '합의된 화면을 구현합니다.',
        status: 'IN_PROGRESS',
        order: 3,
        dueDate: '2026-10-30',
        completedAt: null,
        requiresApproval: false,
        notes: '',
      },
      {
        id: 'example-milestone-qa',
        engagementId: id,
        title: 'QA',
        description: '합의된 기능이 동작하는지 확인합니다.',
        status: 'NOT_STARTED',
        order: 4,
        dueDate: '2026-11-08',
        completedAt: null,
        requiresApproval: false,
        notes: '',
      },
    ],
    reviews: [
      {
        id: 'example-review-1',
        engagementId: id,
        milestoneId: 'example-milestone-design',
        title: 'Design draft',
        status: 'PENDING',
        requestedAt: '2026-09-27',
        reviewedAt: null,
        feedback: '',
        version: 1,
      },
    ],
    files: [
      {
        id: 'example-file-1',
        name: 'Example sitemap.pdf',
        category: 'Planning',
        uploadedBy: 'Admin',
        createdAt: '2026-09-24',
        version: 1,
      },
    ],
    messages: [
      {
        id: 'example-message-1',
        sender: 'Admin',
        body: '디자인 초안을 검토 탭에서 확인해 주세요.',
        createdAt: '2026-09-27',
        isInternal: false,
      },
      {
        id: 'example-message-internal',
        sender: 'Admin',
        body: '내부 메모: 고객에게 보이지 않는 운영 메시지입니다.',
        createdAt: '2026-09-27',
        isInternal: true,
      },
    ],
    changeRequests: [
      {
        id: 'example-change-1',
        engagementId: id,
        title: '문의 폼 필드 추가',
        description: '합의된 문의 폼은 동작합니다. 회사명 필드를 추가하고 싶습니다.',
        classification: 'CHANGE_REQUEST',
        status: 'AWAITING_CUSTOMER_APPROVAL',
        costImpact: '별도 견적 필요. 결제와 연결하지 않습니다.',
        scheduleImpact: '약 2일',
        createdAt: '2026-09-26',
        approvedAt: null,
      },
    ],
    activities: [
      {
        id: 'example-activity-1',
        type: 'REVIEW_REQUESTED',
        actor: 'Admin',
        description: 'Design draft 검토를 요청했습니다.',
        createdAt: '2026-09-27',
      },
      {
        id: 'example-activity-2',
        type: 'MILESTONE_UPDATED',
        actor: 'Admin',
        description: 'Planning 단계를 승인했습니다.',
        createdAt: '2026-09-25',
      },
    ],
    payments: [
      { id: 'example-pay-deposit', label: 'Deposit', amount: 1650000, dueDate: '2026-09-20', status: 'PAID' },
      { id: 'example-pay-interim', label: 'Interim', amount: 990000, dueDate: '2026-10-20', status: 'PENDING' },
      { id: 'example-pay-final', label: 'Final', amount: 660000, dueDate: '2026-11-10', status: 'PENDING' },
    ],
  },
]
