import type { Intake } from './types'

export const mockIntakes: Intake[] = [
  {
    id: 'example-intake-1',
    engagementId: 'example-engagement-1',
    status: 'IN_PROGRESS',
    items: [
      {
        id: 'example-intake-item-1',
        intakeId: 'example-intake-1',
        category: 'Business Information',
        title: '회사 소개',
        description: '서비스와 회사를 한 단락으로 적어 주세요.',
        required: true,
        status: 'APPROVED',
        customerResponse: 'Example Co는 예시 회사입니다.',
        referenceUrl: '',
        adminFeedback: '',
      },
      {
        id: 'example-intake-item-2',
        intakeId: 'example-intake-1',
        category: 'Brand Assets',
        title: '로고 사용 메모',
        description: '로고 파일은 올리지 않습니다. 사용 규칙만 적습니다.',
        required: true,
        status: 'APPROVED',
        customerResponse: '예시 로고는 단색으로 사용합니다.',
        referenceUrl: '',
        adminFeedback: '',
      },
      {
        id: 'example-intake-item-3',
        intakeId: 'example-intake-1',
        category: 'Content',
        title: '첫 화면 문장',
        description: '홈 첫 화면에 둘 문장입니다.',
        required: true,
        status: 'UNDER_REVIEW',
        customerResponse: '예시 문장입니다.',
        referenceUrl: '',
        adminFeedback: '길이를 한 줄로 줄여 주세요.',
      },
      {
        id: 'example-intake-item-4',
        intakeId: 'example-intake-1',
        category: 'Reference Sites',
        title: '참고 사이트',
        description: '톤이 비슷한 공개 사이트 주소입니다.',
        required: false,
        status: 'UPLOADED',
        customerResponse: '',
        referenceUrl: 'https://example.com',
        adminFeedback: '',
      },
      {
        id: 'example-intake-item-5',
        intakeId: 'example-intake-1',
        category: 'Domain / Hosting',
        title: '도메인 희망 이름',
        description: '계정 비밀번호는 적지 않습니다.',
        required: true,
        status: 'NOT_STARTED',
        customerResponse: '',
        referenceUrl: '',
        adminFeedback: '',
      },
      {
        id: 'example-intake-item-6',
        intakeId: 'example-intake-1',
        category: 'Service Requirements',
        title: '추가 메모',
        description: '없어도 제작을 시작할 수 있습니다.',
        required: false,
        status: 'OPTIONAL',
        customerResponse: '',
        referenceUrl: '',
        adminFeedback: '',
      },
      {
        id: 'example-intake-item-7',
        intakeId: 'example-intake-1',
        category: 'Admin Requirements',
        title: '관리 화면에서 보고 싶은 것',
        description: '문의 목록 정도면 충분합니다.',
        required: true,
        status: 'APPROVED',
        customerResponse: '문의 목록만 보면 됩니다.',
        referenceUrl: '',
        adminFeedback: '',
      },
    ],
  },
]
